version: "3.7"
services:
  web:
    build: web
    restart: always
    ports:
      - 6060:6060
    environment:
      - DEBUG=0
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - flask_network


  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=market
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flask_network:

volumes:
  postgres_data:
