"""Added something

Revision ID: e95d6e9792f8
Revises: 5f81987ad3ac
Create Date: 2022-06-27 19:48:26.853800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95d6e9792f8'
down_revision = '5f81987ad3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
